Удалён РДМ компонент у БПЛА
Rxup/space-station-14 pull request #130
Opened 2023-07-09 09:33 UTC by KayzelW

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.

- remove: Ногами вырезан CombatMode у БПЛА

2023-07-09 12:54 UTC, freeze2222 approved these changes

2023-07-09 12:55 UTC, freeze2222 requested changes
Он должен иметь возможность ближнего боя, запрети ему использовать огнестрел.

2023-07-09 17:41 UTC, KayzelW commented
> Он должен иметь возможность ближнего боя, запрети ему использовать огнестрел.

не должен, это пиздец, пусть будет просто тех. дроном

2023-07-09 17:42 UTC, KayzelW commented
И ещё в этом же PR добавил спавнеры их.

2023-07-09 20:54 UTC, KayzelW commented
Шата и мана эти названия файлов

2023-07-10 09:41 UTC, freeze2222 approved these changes

2023-07-10 09:41 UTC, merged