Доделаны карты: 8/16(?)
Rxup/space-station-14 pull request #141
Opened 2023-07-20 18:43 UTC by KayzelW

## Описание PR

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.

- add: Добавлены банкоматы, EFTPOS, дренажи, ящики парамедов на 8/16 карт.

Осталось ещё 8:
![image](https://github.com/Rxup/space-station-14/assets/43700376/2526ab13-4289-4825-b9bf-7440ddbad028)

2023-07-22 06:21 UTC, freeze2222 requested changes
Аврит сломан

2023-07-22 08:13 UTC, KayzelW commented
![image](https://github.com/Rxup/space-station-14/assets/43700376/2fa95b7d-2699-498b-b755-5b110f9964b7)
+раунд нормально начинается на аврите...

2023-07-22 09:07 UTC, freeze2222 approved these changes

2023-07-22 09:09 UTC, merged

2023-07-23 20:25 UTC, KayzelW commented
box и avrite вымерли(по новой)