CentCom roles tweak
Rxup/space-station-14 pull request #166
Opened 2023-07-30 12:54 UTC by Kirillcas

## Описание PR
Уменьшил требоваемое время на все роли ЦК, но добавил две роли по меньше на которых надо отыграть чтобы попасть на роль выше, также чучуть дал больше униформ и заменил некоторые спрайты
- Начальник Безопасности ЦК - 3000 за СБ. 3600 за командный отдел. 900 за ГСБ. 300 за АВД. 600 за приватного офицера СБ ЦК
- Оператор ЦК - 1200 за АВД. 720 за Ассистента ЦК. 3600 за командный отдел
- Представитель ЦК - 1800 за АВД. 720 за Ассистента ЦК. 2100 за капитана. 3600 за командный отдел
- Грусчик ЦК - 2100 за Отдел карго. 720 за Ассистента ЦК
- Приватный Офицер СБ ЦК - 1800 за СБ. 60 за ГСБ
- Ассистент ЦК - 1800 за Инженерию/Медицинский/Сервисные отделы

ЦК больше не будет с доп текстом как у станций (типо свой да)

**Медиа**
НБЦК
![image](https://github.com/Rxup/space-station-14/assets/124053750/31d32c51-eab1-4958-8097-9c0cd183d728)

оЦК
![image](https://github.com/Rxup/space-station-14/assets/124053750/90d841b5-7390-46b7-95c3-844cd35b4474)

ассистент
![image](https://github.com/Rxup/space-station-14/assets/124053750/63d911a9-c650-4849-ba9d-2c2f759156ec)

Опасный Ассистент
![image](https://github.com/Rxup/space-station-14/assets/124053750/3854d683-edc6-4090-8583-b5351bd0bbe8)

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: kirillcas
- add: Добавлено две новые роли ЦК
- add: Добавлена новая форма ЦК и в ЦентШкаф
- remove: Убрано что текст будет написан викиводами....
- tweak: Генератор имён ЦК

2023-07-30 15:26 UTC, KayzelW commented
а ты доступ настроил для них?

2023-07-30 17:17 UTC, KayzelW commented
и это, время на АВД для ПЦК надо больше, чем для ОЦК?

2023-07-30 18:08 UTC, Rxup requested changes

2023-07-30 18:08 UTC, Rxup commented on Resources/Prototypes/Roles/play_time_trackers.yml
> -#start-backmen: brigmed
Бригмед у нас живой

2023-07-30 18:08 UTC, Rxup commented on Resources/Maps/centcomm.yml
> -    - type: LoadedMap
карта цк сейчас сохраняется как map а не как grid по той причине она грузится через gamemapload а не через loadgrid фишка в том чтобы оно было станцией и применился к ней все правила станции она должна быть корректной картой

2023-07-30 19:31 UTC, Kirillcas commented
> и это, время на АВД для ПЦК надо больше, чем для ОЦК?

я решил так сделать ибо пЦК выходит на станцию, от чего получить недовольство от него выше,
и разница 10 часов...

2023-07-30 21:37 UTC, Kirillcas commented on Resources/Maps/centcomm.yml
> -    - type: LoadedMap
Исправил...

2023-07-31 04:42 UTC, Rxup approved these changes

2023-07-31 04:43 UTC, merged