Шаттл торговца...
Rxup/space-station-14 pull request #270
Opened 2023-10-10 17:05 UTC by ponylolkek13

## Описание PR
Компактный шаттл торговца, у дверей доступ ЦК ( кроме раздвижного окна ) на мостике шаттла имеется шкаф с доступам капитана, в нем есть тайзер, 3 пары наручников, пульт управления дверьми и другого по мелочи, рядом есть аптечка с авто-иньекторами, так же есть кнопка изоляции которая задвигает гермозатворы на окнах и  у выхода из шаттла. в хранилище есть пару ящиков, блюспейс предметы, и т.п. В главном холе есть доп. хранилище где есть армейский рюкзак и вещмешок. далее на скрине...
**Медиа**
![Screenshot_153](https://github.com/Rxup/space-station-14/assets/125786317/81308dcc-ae54-4d88-b8c3-18a1cd857cf6)

2023-10-10 17:32 UTC, KTDR228337 commented
Эта проводка просто имба!
Ты хоть проверил шаттл прежде чем делать с ним пр? У тебя консоли и движки справа не будут работать судя по тому что к ним нет НВ проводов. И да, сделай хотя бы 2 ЛКП. И ещё, добавь цветочков.

2023-10-11 15:19 UTC, KayzelW requested changes
@KTDR228337 
Эта проводка просто имба!
Ты хоть проверил шаттл прежде чем делать с ним PR? У тебя консоли и движки справа не будут работать судя по тому что к ним нет НВ проводов. И да, сделай хотя бы 2 ЛКП. И ещё, добавь цветочков.

2023-10-17 15:02 UTC, ponylolkek13 commented
Upd: Обновил проводку и добавил пару цветочков

2023-10-17 16:19 UTC, KTDR228337 commented
> Upd: Обновил проводку и добавил пару цветочков

Покажи. Я проверю.

2023-10-29 09:21 UTC, KTDR228337 commented
@KayzelW ты убери запрос на изменение и принимай

2023-11-10 18:06 UTC, closed without merging