NT Dust-469
Rxup/space-station-14 pull request #276
Opened 2023-10-15 14:49 UTC by KTDR228337

## Описание PR
Новый шаттл для кораблекрушения "Dust 469"
Маппили: cvasoc, KTDR (nFKS), Kukuruz1ch, Chaos_

**Медиа**
*Угловые стены сломаны рендером*
![image](https://github.com/Rxup/space-station-14/assets/140620960/953febe3-7f22-4e71-a859-9050d11f89e4)

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:KTDR
- add: Добавлен новый шаттл для кораблекрушения.

2023-10-15 15:02 UTC, Kirillcas commented
Откуда опять НТ...
"Анонс! НТ также теперь занимается и круиз перевозками!"

2023-10-15 15:03 UTC, KTDR228337 commented
> Откуда опять НТ... "Анонс! НТ также теперь занимается и круиз перевозками!"

Квас сказал так назвать.
Кстати, где купить тур на марс у НТ?

2023-10-15 15:16 UTC, Kirillcas commented
> Квас сказал так назвать. Кстати, где купить тур на марс у НТ?

Не слушай, либо другой компании инициалы поставь, либо также как и у других шаттлов просто название 
"Dust... dedust2 :sunglasses:"

2023-10-15 15:18 UTC, KTDR228337 commented
> > Квас сказал так назвать. Кстати, где купить тур на марс у НТ?
> 
> Не слушай, либо другой компании инициалы поставь, либо также как и у других шаттлов просто название "Dust... dedust2 😎"

Ладно :shelterwaa:

2023-10-16 11:49 UTC, KTDR228337 commented
@KayzelW

2023-10-26 23:09 UTC, Rxup requested changes
Found no latejoin spawn points on shwrDust

2023-10-27 06:07 UTC, KTDR228337 commented
> Found no latejoin spawn points on shwrDust

Так это для кораблекрушения
Там не нужен спавн после начала раунда и естественно нет никакого прибытия

2023-10-27 07:23 UTC, Kirillcas commented
> Так это для кораблекрушения Там не нужен спавн после начала раунда и естественно нет никакого прибытия

Тэсты так фэйлятся
У `adventurer.yml` есть точка лэйтджойна
Ставь если коротко

2023-10-27 07:40 UTC, KTDR228337 commented
> > Так это для кораблекрушения Там не нужен спавн после начала раунда и естественно нет никакого прибытия
> 
> Тэсты так фэйлятся У `adventurer.yml` есть точка лэйтджойна Ставь если коротко

Ох... Ну я сейчас не могу. @KayzelW можешь сделать пожалуйста?

2023-10-27 08:06 UTC, KayzelW commented
> > > Так это для кораблекрушения Там не нужен спавн после начала раунда и естественно нет никакого прибытия
> > 
> > 
> > Тэсты так фэйлятся У `adventurer.yml` есть точка лэйтджойна Ставь если коротко
> 
> Ох... Ну я сейчас не могу. @KayzelW можешь сделать пожалуйста?

не то чтобы...

2023-10-27 08:31 UTC, KTDR228337 commented
> > > > Так это для кораблекрушения Там не нужен спавн после начала раунда и естественно нет никакого прибытия
> > > 
> > > 
> > > Тэсты так фэйлятся У `adventurer.yml` есть точка лэйтджойна Ставь если коротко
> > 
> > 
> > Ох... Ну я сейчас не могу. @KayzelW можешь сделать пожалуйста?
> 
> не то чтобы...

Ты можешь :jokerge:

2023-11-25 11:19 UTC, closed without merging