Magicians Antag v1
Rxup/space-station-14 pull request #337
Opened 2023-11-18 15:46 UTC by FilinSep

## Описание PR

Маги антагонисты на основе каперов (нету собственной роли во вкладке антагонистов)
если кто-то хочет сделать роль во вкладке - сделайте.

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

- add: Добавлен аплинк магов
- add: Добавлены маги антагонисты (событие)

2023-11-21 12:22 UTC, Rxup requested changes

2023-11-21 12:22 UTC, Rxup commented on Resources/Prototypes/Backmen/GameRules/MagiciansAntag/MagicUplink/uplink_mana.yml
> +  id: UplinkMagicMana
использовать
```- type: material
  id: Bluespace
  name: bluespace
  icon: /Textures/Backmen/Objects/Materials/materials.rsi/bluespace.png
  color: "#53a9ff"
  stackEntity: MaterialBluespace
  price: 15``
В коде уже есть.

2023-11-21 12:22 UTC, Rxup commented on Resources/Prototypes/Backmen/GameRules/MagiciansAntag/MagicUplink/specific_objects.yml
> +    preset: StorePresetMagicalUplink
Могут использовать все? не пойдет.

2023-11-21 12:22 UTC, Rxup commented on Content.Server/Backmen/GameTicking/Rules/MagiciansRuleSystem.cs
> +                var mob = Spawn("MobHuman", _random.Pick(spawns));
Почему только люди? есть они (типо демоны), фелиниды (демонческая кровь)

2023-11-21 12:22 UTC, Rxup commented on Content.Server/Backmen/GameTicking/Rules/MagiciansRuleSystem.cs
> +            var magicianGear = _prototypeManager.Index<StartingGearPrototype>("MagiciangGear");
Прототип вынести в yml

2023-11-21 12:22 UTC, Rxup commented on Content.Server/Backmen/GameTicking/Rules/MagiciansRuleSystem.cs
> +                if (meta.EntityPrototype?.ID != "SpawnPointCaptain" || xform.ParentUid != mags.MagicianShip)
сделать нормальный спавн поинт и свой карабль, сделать на новой карте, и FTL (бсс) до станции. СМ: SpecForces. и также им можно сделать мини базу и WhiteList для консоли магов на шаттле магов.

2024-02-03 15:45 UTC, Kirillcas commented
Минус

2024-02-03 15:45 UTC, closed without merging