New books
Rxup/space-station-14 pull request #449
Opened 2024-02-04 17:37 UTC by Devian505

## Add two new books

**Медиа**
![2024-02-04_19-01-22](https://github.com/Rxup/space-station-14/assets/75939344/a97802a4-b1e1-4e7d-802a-b34de20a53e5)
![2024-02-04_19-00-49](https://github.com/Rxup/space-station-14/assets/75939344/46d26fe1-e5e7-49c6-a857-502699d080f6)

:cl:
- add: book PaperWork 6, book Passion in Security 2.

2024-02-05 17:09 UTC, Egorcha commented
Считаю должным добавить книги, а вот кокспайк это лишнее (но книг желательно побольше, и на данную тематику и на разные другие)

2024-02-06 05:04 UTC, Kirillcas requested changes

2024-02-06 05:04 UTC, Kirillcas commented on Resources/Prototypes/Backmen/Entities/Structures/Furniture/cock_spike.yml
> +  - type: Construction
:harold: это точно не для легального получения, а и еще ты не сделал сам прототип сборки и прототип меню крафта, так, на будущее

Поэтому нод стула Верни чтобы это можно было отвёрткой разобрать

2024-02-06 05:09 UTC, Kirillcas commented
Иии да, у тебя тэст упал из-за несуществующего нода `CockSpike`

2024-02-06 13:02 UTC, Devian505 commented
Da fuck. -_-

2024-02-06 13:15 UTC, Devian505 commented on Resources/Textures/Backmen/Structures/Furniture/cock_spike.rsi/meta.json
> +    "copyright": "by Devian505",
Okey, edited this.

2024-02-06 13:18 UTC, Devian505 commented on Resources/Prototypes/Catalog/Fills/Books/bookshelf.yml
Niga you crazy. All this stuff have 0.1
![image](https://github.com/Rxup/space-station-14/assets/75939344/2d6c67c9-26e8-4b24-909c-5edd9cb468f3)

2024-02-06 13:21 UTC, Devian505 commented on Resources/Prototypes/Backmen/Entities/Objects/Misc/authorbooks.yml
> +  name: Бумажная работа. Ордер на любовь
Bruh, all names in this authorbooks.yml russian.

2024-02-06 13:23 UTC, Devian505 commented on Resources/Prototypes/Backmen/Entities/Structures/Furniture/cock_spike.yml
> +  - type: Construction
Fine. I change node. But i create this shit for admin bc players can spam screams when buckled.

2024-02-07 00:10 UTC, PvrG commented
Я не нашла никаких картинок, поэтому держите эту
![Screenshot_20231108_223028_Discord](https://github.com/Rxup/space-station-14/assets/143443369/a0dfed7a-f741-4328-84ce-b32d9b78b1a1)

2024-02-07 04:14 UTC, Kirillcas commented on Resources/Prototypes/Backmen/Entities/Objects/Misc/authorbooks.yml
> +  name: Бумажная работа. Ордер на любовь
`Resources/Locale/ru-RU/ss14-ru/prototypes/backmen/entities/objects/misc/authorbooks.ftl`

Line 31
Line 33

2024-02-07 14:51 UTC, Kirillcas approved these changes

2024-02-07 17:09 UTC, merged