Refactor SpecForcesSystem
Rxup/space-station-14 pull request #589
Opened 2024-04-29 12:22 UTC by Roudenn

## Описание PR
Данный ПР оптимизирует код спецсил, добавляя в него систему прототипов.

**Краткая документация о прототипе:**
SpecForceTeam прототип позволяет добавлять администраторам свои спецотряды через AdminBus, а также гораздо упрощает их добавление. Прототип позволяет изменять много параметров, однако принцип работы спавна в основном заимствован из прошлой версии кода, то есть:
- Спавнятся все сущности из списка guaranteedSpawn
- Подсчитывается оставшееся количество ролей, которые можно заспавнить
- По порядку спавнятся все сущности из списка specForceSpawn. Если список закончился и всё ещё нужно заспавнить роли, цикл начинается заново, пока все роли не будут заспавнены.

**Текущие проблемы**
- Команда callspecforces не даёт ответы в формате выпадающего списка (код там пока закомментирован, мне требуется помощь чтобы понять как правильно индексировать все варианты)
- Название отряда в манифесте конца раунда неверно отображает имя (флюент не работает дважды в манифесте, проблема вроде как распространена и на другой похожий код)

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [X] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [X] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [X] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

2024-04-29 12:46 UTC, Roudenn commented on Content.Server/Backmen/Administration/Commands/CallSpecForcesCommand.cs
Почему-то внутри команды не могу вызвать прототип, выдаёт ошибку "На данном моменте этот класс нельзя вызвать"
Всё равно очень хотелось бы добавить сюда енумерабл и нормальную систему выпадающего списка для удобства админам

2024-04-29 12:48 UTC, Roudenn commented on Content.Server/Backmen/SpecForces/SpecForcesSystem.cs
> +            var announcementSound = new SoundPathSpecifier(proto.AnnouncementSoundPath);
Здесь у меня не получилось с аннаунсмент саундом и нуллами, поэтому я пошёл на вот такие костыли и продублировал код... Не уверен но возможно его тут можно оптимизировать

2024-04-29 19:02 UTC, Rxup requested changes

2024-04-29 19:02 UTC, Rxup commented on Content.Server/Backmen/SpecForces/SpecForcesSystem.cs
> +        foreach (var mob in proto.GuaranteedSpawn)
тут не должно быть такого, см у оффов есть списки с весами и шансами и группой.
см. ```EntitySpawnCollection.GetSpawns(component.SpawnEntries);```
см. 
```csharp
    /// <summary>
    /// Selects what entities can be given out by the giver.
    /// </summary>
    [DataField("spawnEntries", required: true)]
    public List<EntitySpawnEntry> SpawnEntries = default!;
```

```yml
  - type: LimitedItemGiver
    spawnEntries:
      - id: PresentRandom
        orGroup: present
      - id: PresentRandomCash
        prob: 0.20
        orGroup: present
      - id: PresentRandomAsh
        prob: 0.05
        orGroup: present
```
как пример

2024-05-01 11:10 UTC, Roudenn commented on Content.Server/Backmen/SpecForces/SpecForcesSystem.cs
> +        foreach (var mob in proto.GuaranteedSpawn)
Ентри здесь просто не подходит, поскольку спецсилы требуют возможность для чёткой балансировки, и рандом тут будет лишним
В старой версии кода рандом был только со спавном ОСО, сейчас же я просто добавил ОСО гарантом к Альфе и РХБЗЗ

2024-05-02 05:49 UTC, Rxup commented on Content.Server/Backmen/SpecForces/SpecForcesSystem.cs
> +        foreach (var mob in proto.GuaranteedSpawn)
смотри внимательней, это делает список, рандом не обязателен, может просто выбрать случайно 1 из 3 сущностей, что в принципе тоже оптимально. т.е. крутая функциональность просто в запас

2024-05-02 05:54 UTC, Rxup commented on Content.Server/Backmen/Administration/Commands/CallSpecForcesCommand.cs
> +            1 => CompletionResult.FromHintOptions(variants, "Тип вызова"),
эээээ не понятно зачем этот ```variants``` запихни в 1 строку

2024-05-02 05:54 UTC, Rxup requested changes
сделай список с возможностью рандома, но рандом сейчас добавлять не надо.

2024-05-02 21:24 UTC, Rxup approved these changes

2024-05-02 21:49 UTC, merged