computers
Rxup/space-station-14 pull request #65
Opened 2023-05-01 19:16 UTC by Semantic4780

## 
Описание PR

computers.maybe we need it

**Медиа**

![pc sssp](https://user-images.githubusercontent.com/132294047/235513869-f43157ae-3898-4c5a-b9da-40096877e9e9.png)
![pc win](https://user-images.githubusercontent.com/132294047/235513870-f519b2ce-7a53-472d-98dd-10d1c17d5be6.png)
![pc](https://user-images.githubusercontent.com/132294047/235513871-b50660d3-07e8-4e84-859d-77feb58a0029.png)
![pc nanotrasen](https://user-images.githubusercontent.com/132294047/235513872-106fe95d-75fb-462d-8a0a-23583e3db1e3.png)
![pc sindy](https://user-images.githubusercontent.com/132294047/235513873-b4a81d41-a929-4859-8d3b-944cd5b5e644.png)

**Проверки**

- [- ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [+ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ -] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [+ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: commi hamlet
- add: Добавлено компьютерное оборудование нанотрейсен!
- add: Добавлено компьютерное оборудование сссп!
- add: Добавлено компьютерное оборудование синдиката!

2023-05-01 19:19 UTC, freeze2222 requested changes
462 коммита и 129 тысяч строк кода? Ты, видимо, давно не обновлял сборку...

2023-05-01 19:20 UTC, freeze2222 commented
И для того чтобы чекбоксы работали, ставь x между скобок, вот так [x]

2023-05-01 19:21 UTC, Semantic4780 commented
> 462 коммита и 129 тысяч строк кода? Ты, видимо, давно не обновлял сборку...



> И для того чтобы чекбоксы работали, ставь x между скобок, вот так [x]

в проверках типо? я просто недопонимаю что ещё да как

2023-05-01 19:22 UTC, Semantic4780 commented
> 462 коммита и 129 тысяч строк кода? Ты, видимо, давно не обновлял сборку...

а это плохо? хаха

2023-05-01 19:24 UTC, freeze2222 commented
> > 462 коммита и 129 тысяч строк кода? Ты, видимо, давно не обновлял сборку...
> 
> а это плохо? хаха

Нажми кнопку sync fork в твоём репозитории справа вверху.

2023-05-01 21:02 UTC, Semantic4780 commented
> > > 462 коммита и 129 тысяч строк кода? Ты, видимо, давно не обновлял сборку...
> > 
> > 
> > а это плохо? хаха
> 
> Нажми кнопку sync fork в твоём репозитории справа вверху.

так и не смог найти, скажи поподробней

2023-05-04 04:11 UTC, freeze2222 commented
Ты явно сделал что-то не так, создай новый ПР как разберёшься.

2023-05-04 04:11 UTC, closed without merging