Fix Blob
Rxup/space-station-14 pull request #658
Opened 2024-06-21 15:11 UTC by Roudenn

## Описание PR
- Многие цифры, напрямую связанные с игровыми этапами режима Blob перенесены в CVar'ы
- Теперь блоб не может расти или атаковать из мёртвых клеток
- При блобе всегда форсированно спавнится 8 РХБЗЗ
- Отражающие плитки блоба отражают с шансом 60% вместо 90%, а прочность плитки повышена с 100 до 125. Это позволяет сносить эти плитки при помощи лазерных винтовок и пушек РХБЗЗ, однако попутно отхватывая от отразившихся снарядов.

**Проверки**

- [X] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [X] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [X] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [X] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: Rouden
- tweak: Отражающие плитки блоба теперь проще уничтожить лазером.
- fix: Теперь блоб не может расти или атаковать из мёртвых клеток.

2024-06-26 14:47 UTC, Rxup commented on Content.Server/Backmen/GameTicking/Rules/BlobRuleSystem.cs
> +            case BlobStage.Critical when blobCore.Comp.BlobTiles.Count >= _cfg.GetCVar(CCVars.BlobTilesWin):
я же писал! нужно сделать станции новой компонент StationBlobConfig и добавить его в прототипы карт

2024-06-26 15:00 UTC, Roudenn commented on Content.Server/Backmen/GameTicking/Rules/BlobRuleSystem.cs
> +            case BlobStage.Critical when blobCore.Comp.BlobTiles.Count >= _cfg.GetCVar(CCVars.BlobTilesWin):
Странно, мне казалось мы закрыли эту тему в дискорде
Но ладно я передумал, все же на разных станциях разный онлайн а потому стоит сравнить разное количество специл при разном количестве тайлов блоба, так что переделаю наверное завтра

2024-06-29 00:21 UTC, Rxup requested changes

2024-06-29 00:21 UTC, Rxup commented on Content.Server/Backmen/Blob/BlobCoreActionSystem.cs
> +    [Dependency] private readonly IEntityManager _entMan = default!;
````[Dependency] private readonly IEntityManager _entMan = default!;``` убрать не должно быть использовано в EntitySystem

2024-06-29 00:21 UTC, Rxup commented on Content.Server/Backmen/Blob/BlobCoreActionSystem.cs
> +                var nearTileComp = _entMan.GetComponent<BlobTileComponent>(nearTile.Value);
должно быть ```_tileQuery``` и вообще не понятно что проверяет

2024-06-29 00:21 UTC, Rxup commented on Content.Server/Backmen/Blob/BlobCoreActionSystem.cs
> +            return;
тоже должно быть с ```_tileQuery``` и не понятно зачем оно

2024-06-29 00:21 UTC, Rxup commented on Content.Server/Backmen/GameTicking/Rules/BlobRuleSystem.cs
> +            var stationConfig = EnsureComp<StationBlobConfigComponent>(stationUid.Value);
Не понятно зачем его задавать станции, есть ```CompOrNull``` если null то делаеть по умолчанию

2024-06-29 00:21 UTC, Rxup commented on Content.Server/Backmen/GameTicking/Rules/BlobRuleSystem.cs
> +    private void CheckChangeStage(Entity<BlobCoreComponent> blobCore, EntityUid stationUid, BlobRuleComponent blobRuleComp, StationBlobConfigComponent stationConfig)
EntityUid stationUid
заменить на
Entity<StationBlobConfigComponent?> stationUid

2024-06-29 00:21 UTC, Rxup commented on Content.Server/Backmen/SpecForces/SpecForcesSystem.cs
> +        if (!CallOps(Rxbzz, "ДСО", stationConfig.SpecForceAmount))
почему вариант работы от онлайна не подходит? сделай для блоба другую команду тогда уже. костылить систему не вижу смысла.

2024-06-30 17:35 UTC, closed without merging