Fix Cancer mouse + RXBZZ shuttle
Rxup/space-station-14 pull request #682
Opened 2024-07-08 19:31 UTC by Roudenn

## Описание PR
 - Раковую мышь теперь нельзя съесть, а также ей добавлен спавнер гост роли
 - Обновлён шаттл РХБЗЗ: добавлен медблок, пофикшены скрубберы, 

**Проверки**
- [X] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [X] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [X] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [X] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
:cl: Rouden
- fix: Теперь мышь заражённая вирусом Блоба появляется только когда за неё заходит игрок.

2024-07-09 05:54 UTC, Rxup commented on Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
> -  - type: SolutionContainerManager
а это почему?

2024-07-09 06:17 UTC, Roudenn commented on Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
> -  - type: SolutionContainerManager
Разве это не даёт возможность съесть мышь? Если нет то надо бы вернуть

2024-07-09 13:08 UTC, Rxup commented on Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
> -  - type: SolutionContainerManager
- type: FelinidFood
- type: Food
и мб что-то другое

2024-07-11 16:30 UTC, Rxup requested changes
все еще не фиксит то что нужно

2024-07-11 16:44 UTC, Roudenn commented
> все еще не фиксит то что нужно

Кроме контейнер солюшен что надо исправить?

2024-07-15 22:46 UTC, Rxup commented
надо пересобрать прототип мыши и убрать из него лишние компоненты:
type: FelinidFood
type: Food

либо при спавне удаляй их

2024-07-16 14:04 UTC, Roudenn commented
> надо пересобрать прототип мыши и убрать из него лишние компоненты: type: FelinidFood type: Food
> 
> либо при спавне удаляй их

Сделал так чтобы удалялось при спавне гостспавнером все компоненты с едой

2024-07-17 02:03 UTC, merged