Fix blob tile count
Rxup/space-station-14 pull request #693
Opened 2024-07-17 18:47 UTC by Roudenn

## Описание PR
Данный ПР исправляет код BlobRule, а также вносит правки в BlobSpawnRule.
- Все тайлы всех блобов теперь суммируются при подсчёте поднятия уровня угрозы блоба
- Вместе с этим реактором был удалён ивент BlobChangeLevelEvent за ненадобностью, а код вызова РХБЗЗ был перенесён из SpecForcesSystem в BlobRuleSystem.
- Теперь мышь блоба не может появиться при ивентах с миграцией крыс
- Максимальное количество блобов от BlobSpawn уменьшено c 3 до 2, а также этот ивент может появиться лишь единожды за раунд.

**Проверки**
- [X] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [X] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [X] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [X] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

2024-07-18 01:24 UTC, Rxup requested changes

2024-07-18 05:43 UTC, Roudenn commented on Content.Server/Backmen/GameTicking/Rules/BlobRuleSystem.cs
> +            blobTilesCount += comp.BlobTiles.Count;
По идее я хотел сделать так, чтобы все тайлы одной станции сливались в 1, но видимо что-то напутал

2024-07-18 05:45 UTC, Roudenn commented on Resources/Prototypes/_Backmen/GameRules/events.yml
> +    maxOccurrences: 1 # can only happen once per round
В теории тогда может появиться 2 блоба подряд, то есть уже 4 или 2 при низком онлайне, это очень плохо когда на станции больше чем 1 блоб

2024-07-18 05:48 UTC, Roudenn commented on Content.Server/Backmen/GameTicking/Rules/BlobRuleSystem.cs
> -                blobCore.Comp.Points = 99999;
В будущем планирую рефактор очков для блоба т. к. щас он бесконечно наделать может проспамив ресурсным блобами, а так это просто лишние лаги в конце раунда

2024-07-18 05:55 UTC, Roudenn commented on Content.Server/Backmen/GameTicking/Rules/BlobRuleSystem.cs
> +                var specForceTeam = stationUid.Comp?.SpecForceTeam ?? Rxbzz;
Дело в том что этот ивент больше нигде не используется, так ещё и запрашивает точное ядро блоба которое повысило уровень, хоть у нас такого и нет после того как все тайлы блобов начали складываться.

Я не крутой программист чтобы утверждать как лучше, но все же блоб это большая и недопиленная система, а спецсилы отполированная. Стоит ли вызывать отполированную систему в недопиленной, или вызывать недопиленную в отполированной?

2024-07-18 08:45 UTC, Roudenn commented on Content.Server/Backmen/GameTicking/Rules/BlobRuleSystem.cs
> -                blobCore.Comp.Points = 99999;
Если очень хочется оставить эту фишку, то в CheckChangeStage надо ещё и закидывать список со всеми ядрами блобов и давать им бесконечные очки, спрашивается зачем так усложнять ради по факту бесполезной фишки

2024-07-18 08:45 UTC, Roudenn commented on Resources/Prototypes/_Backmen/GameRules/events.yml
> +    maxOccurrences: 1 # can only happen once per round
Повысить тогда длинну ивента блоба чтобы хотя бы подряд 2 ивента не могло выскочить через кд?

2024-07-18 08:46 UTC, Roudenn commented on Content.Server/Backmen/GameTicking/Rules/BlobRuleSystem.cs
> +            blobTilesCount += comp.BlobTiles.Count;
Эту часть кода переработал через Dictionary

2024-07-18 09:11 UTC, Rxup commented on Content.Server/Backmen/GameTicking/Rules/BlobRuleSystem.cs
> -                blobCore.Comp.Points = 99999;
У действий блоба есть гкд, и действия делаются в фоне, что в принципе не будет лагать хоть все станция блобов

2024-07-18 09:11 UTC, Rxup commented on Content.Server/Backmen/GameTicking/Rules/BlobRuleSystem.cs
> -                blobCore.Comp.Points = 99999;
набор очков как в 13.... еще в 13... у блоба есть прок на бесплатный тык, без затраты очков.

2024-07-18 09:14 UTC, Roudenn commented on Content.Server/Backmen/GameTicking/Rules/BlobRuleSystem.cs
> -                blobCore.Comp.Points = 99999;
> набор очков как в 13.... еще в 13... у блоба есть прок на бесплатный тык, без затраты очков.

Вот это уже в другом рефакторе может быть который я когда-нибудь сделаю
Так получается делать как я написал чтобы всем блобам выдавало бесконечные очки через форич?

2024-07-18 13:30 UTC, Rxup commented on Content.Server/Backmen/GameTicking/Rules/BlobRuleSystem.cs
> -                blobCore.Comp.Points = 99999;
в конце раунда вообще смысла нет, если блоб победил у него и так должно быть их много! и на всякий передавай в BlobChangeLevelEvent - BlobCore, малоли будем еще что делать для ядра во время события.

2024-07-18 13:46 UTC, Roudenn commented on Content.Server/Backmen/GameTicking/Rules/BlobRuleSystem.cs
> -                blobCore.Comp.Points = 99999;
> в конце раунда вообще смысла нет, если блоб победил у него и так должно быть их много! и на всякий передавай в BlobChangeLevelEvent - BlobCore, малоли будем еще что делать для ядра во время события.

Дело в том что нельзя передавать, можно передать только все ядра станции одной списком
Тогда передаём список?

2024-07-18 13:47 UTC, Roudenn commented on Content.Server/Backmen/GameTicking/Rules/BlobRuleSystem.cs
>                  _chatSystem.DispatchGlobalAnnouncement(Loc.GetString("blob-alert-detect"),
Окей поправим

2024-07-19 02:24 UTC, Rxup commented on Content.Server/Backmen/GameTicking/Rules/BlobRuleSystem.cs
> +            CheckChangeStage(blobTiles.Key, component, blobCores, blobTiles.Value);
всмысле? нужно ядра блоба только со станции! т.е. не всем ядрам а только тем кто есть на станции!

2024-07-19 12:03 UTC, Roudenn commented on Content.Server/Backmen/GameTicking/Rules/BlobRuleSystem.cs
> +            CheckChangeStage(blobTiles.Key, component, blobCores, blobTiles.Value);
Пофиксил, теперь передаю в проверку смены стадии сразу Dictionary с станциями и их списком блобов, честно сказать такие структуры выглядят страшно, но оно теперь вроде правильно работает

2024-07-22 12:47 UTC, merged