[Tweak] Blob Refactor Part 1: General Rewrite
Rxup/space-station-14 pull request #703
Opened 2024-07-24 18:34 UTC by Roudenn

## Описание PR
Данный ПР обновляет принцип роста блоба, делая его более базированным на тавер-дефенс чем полную атаку, а также значительно обновляет его код.

Весь этот ПР это 1 часть, во 2 части будут добавлены новые типы тайлов и проведён ребаланс экономики.

- Стоимость роста в космос увеличена до x2.5 от обычной
- Обычные клетки нельзя ставить далеко от блоб узлов
- Убраны действия Помощь и Телепорт к случайному узлу за ненадобностью
- Блоб не может расти от уже мёртвых клеток, он может только их атаковать
- Теперь после убийства блоба и его повторного появления корректно поднимаются уровни угрозы
- Добавлено действие для понижения тайла до обычного
- Ребаланс цен для разделения и переноса ядра
- Количество очков теперь отображается вплоть до 500

##  В прогрессе:
- [x] Пофиксить рост тайлов и атаку возле мёртвых клеток
- [x] Пофиксить перенос ядра (нужно как-то обменять компоненты между узлом и ядром которые меняются местами)
- [x] Добавить актион для даунгрейда блоб тайла до обычного
- [ ] Перепротестировать все функции блоба
- [x] Исправить кулдауны установки тайлов (GDc)
- [ ] Сделать так чтобы каждое ядро могло контролировать только свои клетки
- [x] Переписать гайдбук на блоба
- [x] Пофиксить блоб пульсы и систему ресурсных блобов

**Протестировать:**
- [x] Рост в космос и работает ли в динамике CVar
- [X] Поп Апы
- [x] Локализация

## Технические детали
- Реорганизация многих файлов: перенос некоторых компонентов в Shared, удаление неиспользуемых систем в Shared и Client папках, разделение текстур и прототипов на Блоб Мобов и Блоб Тайлы
- Переписан и оптимизирован код во многих местах, наиболее сильные изменения были в BlobCoreSystem.
- Оптимизированы все ивенты для установки новых блоб тайлов через действия: все они работают 1 ивентом с указанными параметрами
- Ликвидация всех тайлов при уничтожении ядра перенесена в CPUJob для меньших пролагов
- Исправлено множество багов (включая ошибку при добавлении Objective)
- Добавлено множество удобных методов для внешней работы с блобом (GetNearNode, полностью обновлённый TransformBlobTile, ConnectBlobTile и так далее)
- Реорганизован BlobCoreComponent: многая информация теперь хранится в Dictionary типе данных. BlobTileType теперь играет гораздо более важную роль из-за этого
- Сильно почищен код (исправлены предупреждения и CPUJob переделаны через Primary Constructor)

**Изменения**

:cl: Rouden
- tweak: Антагонист Блоб был значительно переработан.

2024-07-24 18:44 UTC, Roudenn reviewed
Вот в этих местах нужна помощь с кодом

2024-07-24 18:44 UTC, Roudenn commented on Content.Server/Backmen/Blob/BlobCoreActionSystem.cs
> +            var nearTile = mobAdjacentTiles.Select(indices=> _mapSystem.GetAnchoredEntities(gridUid.Value, grid, indices)
Это надо переписать в Foreach, поскольку нужно чтобы если не получилось вырастить тайл со стороны где мёртвый блоб, оно пробовало ещё и другие стороны а не просто обрывалось на месте

2024-07-24 18:44 UTC, Roudenn commented on Content.Server/Backmen/Blob/BlobObserverSystem.cs
> +        /*var nodeNodeComp = EnsureComp<BlobNodeComponent>(blobTile.Value);
Вот тут надо сделать так чтобы BlobNodeComponent узла и ядра менялись между собой, я не смог это реализовать вот так и не знаю до конца как сделать получше

2024-07-25 02:24 UTC, Rxup commented on Content.Server/Backmen/Blob/BlobCoreActionSystem.cs
> +            if (_tileQuery.HasComponent(args.Target))
TryComp

2024-07-25 02:26 UTC, Rxup commented on Content.Server/Backmen/Blob/BlobCoreActionSystem.cs
> +            var nearTile = mobAdjacentTiles.Select(indices=> _mapSystem.GetAnchoredEntities(gridUid.Value, grid, indices)
используй Rider он может через лапочку переделать в foreach

2024-07-25 02:27 UTC, Rxup commented on Content.Server/Backmen/Blob/BlobCoreActionSystem.cs
> -                    _gridFixture.Merge(tilePos.GridUid.Value, gridUid.Value, (Vector2i) locPos, Transform(gridUid.Value).LocalRotation);
почему этот код был убран?

2024-07-25 05:24 UTC, Roudenn commented on Content.Server/Backmen/Blob/BlobCoreActionSystem.cs
> +            var nearTile = mobAdjacentTiles.Select(indices=> _mapSystem.GetAnchoredEntities(gridUid.Value, grid, indices)
> используй Rider он может через лапочку переделать в foreach

Разве он может так из линкью в форич? Обычно он предлагает форич в линкью переделать, а вот наоборот не знал что способен

2024-07-25 05:26 UTC, Roudenn commented on Content.Server/Backmen/Blob/BlobCoreActionSystem.cs
> -                    _gridFixture.Merge(tilePos.GridUid.Value, gridUid.Value, (Vector2i) locPos, Transform(gridUid.Value).LocalRotation);
Он был закомментирован, внутри ифа засоряет пол экрана что неудобно чтоб понять код, если что потом можно будет вернуть

2024-07-25 09:15 UTC, Roudenn commented on Content.Server/Backmen/Blob/BlobCoreActionSystem.cs
> +            var nearTile = mobAdjacentTiles.Select(indices=> _mapSystem.GetAnchoredEntities(gridUid.Value, grid, indices)
Смог исправить, теперь блоб там расти может нормально вокруг мёртвых клеток

2024-07-25 09:39 UTC, Roudenn commented on Content.Server/Backmen/Blob/BlobCoreActionSystem.cs
> +            if (_tileQuery.HasComponent(args.Target))
Сделано

2024-07-25 09:39 UTC, Roudenn commented on Content.Server/Backmen/Blob/BlobObserverSystem.cs
> +        /*var nodeNodeComp = EnsureComp<BlobNodeComponent>(blobTile.Value);
Смог сделать через хешовые переменные, не уверен что не говнокод но оно работает

2024-08-04 16:31 UTC, Rxup commented on Content.Server/Backmen/Blob/BlobCoreSystem.cs
> +            || !TryComp<BlobCoreComponent>(blobObserverComponent.Core, out _))
HasComp
Если не нужно out var в TryComp

2024-08-04 16:32 UTC, Rxup commented on Content.Server/Backmen/Blob/BlobCoreSystem.cs
> +        if (args.Mind.OwnedEntity == null)
args.Mind.OwnedEntity == null || TerminatedOrDeleted(args.Mind.OwnedEntity)

2024-08-04 16:33 UTC, Rxup commented on Content.Server/Backmen/Blob/BlobCoreSystem.cs
> +        TryComp<BlobNodeComponent>(uid, out var nodeComp);
CompOrNull

2024-08-11 19:32 UTC, Rxup commented on Content.Server/Backmen/Blob/BlobCarrierSystem.cs
> +        if (_mind.GetMind(uid) != null)
HasComp<ActorComponent>(uid)

2024-08-11 19:33 UTC, Rxup commented on Content.Server/Backmen/Blob/BlobCoreActionSystem.cs
> -    //[Dependency] private readonly GridFixtureSystem _gridFixture = default!;
по прежнему не вернул комментарии с grid merge

2024-08-11 19:58 UTC, Rxup commented on Content.Server/Backmen/Blob/BlobCoreSystem.cs
> +    public bool TryKillBlobTile(EntityUid uid)
лучше сделать через событие да и вызывать стандартную функцию когда делается действие destroy

2024-08-14 08:24 UTC, Roudenn commented on Content.Server/Backmen/Blob/BlobCoreSystem.cs
> +    public bool TryKillBlobTile(EntityUid uid)
Про стандартную функцию, какую именно и как?

2024-08-17 17:43 UTC, Roudenn commented on Content.Server/Backmen/Blob/BlobCoreActionSystem.cs
> -    //[Dependency] private readonly GridFixtureSystem _gridFixture = default!;
Пытался расскоментить, ничего не происходит когда пытаешься тыкнуть на другой грид

2024-08-19 17:10 UTC, Roudenn commented
@Rxup без плейтеста можно будет обойтись?

2024-08-25 18:18 UTC, Roudenn commented on Content.Server/Backmen/Blob/BlobCoreActionSystem.cs
> -    //[Dependency] private readonly GridFixtureSystem _gridFixture = default!;
Комментарий вернул

2024-09-18 10:41 UTC, Rxup requested changes

2024-09-18 10:41 UTC, Rxup commented on Content.Server/Backmen/Blob/BlobCoreActionSystem.cs
> -        blobCoreComponent.NextAction = _gameTiming.CurTime + TimeSpan.FromMilliseconds(333); // GCD?
почему удален GCD?

2024-09-18 10:41 UTC, Rxup commented on Content.Client/Backmen/Blob/BlobCoreSystem.cs
> -public sealed class BlobCoreSystem : SharedBlobCoreSystem
почему удалена с клиента реализация?

2024-09-18 10:41 UTC, Rxup commented on Content.Server/Backmen/GameTicking/Rules/BlobRuleSystem.cs
> +                _chatSystem.DispatchGlobalAnnouncement(
почему Global?

2024-09-18 10:41 UTC, Rxup commented on Content.Server/Backmen/GameTicking/Rules/Components/BlobRuleComponent.cs
> +    public Dictionary<EntityUid, HashSet<Entity<BlobCoreComponent>>> StationCores = [];
Зачем это?

2024-09-18 10:41 UTC, Rxup commented on Content.Shared/Backmen/Blob/Components/BlobCoreComponent.cs
> +    public Dictionary<BlobTileType, ProtoId<EntityPrototype>> TilePrototypes = new()
Должен быть не ```ProtoId<EntityPrototype>``` а ```EntProtoId<BlobTileComponent>```

2024-09-18 11:18 UTC, Rxup requested changes

2024-09-18 11:18 UTC, Rxup commented on Content.Server/Backmen/Blob/BlobNodeSystem.cs
> +        RaiseLocalEvent(ent, new BlobSpecialGetPulseEvent());
убрать лишний broadcast, вернуть старый эвент, этот использовать в системе и в том эвенте и раздавать новый только для вложенных

2024-09-18 11:18 UTC, Rxup commented on Content.Server/Backmen/Blob/BlobNodeSystem.cs
> +            RaiseLocalEvent(special.Value.Value, ev);
перенести на срабатывания по BlobNode при ```BlobTileGetPulseEvent```
и дальше раздавать BlobSpecialGetPulseEvent на связанные

2024-09-18 17:46 UTC, Roudenn commented on Content.Server/Backmen/GameTicking/Rules/BlobRuleSystem.cs
> +                _chatSystem.DispatchGlobalAnnouncement(
Имя станции указано, это чтобы сразу во всем секторе все игроки слышали а не только на одной станции, нужно чтобы РХБЗЗ знало на какую конкретно станцию лететь потому что в теории их может быть несколько

2024-09-18 17:47 UTC, Roudenn commented on Content.Client/Backmen/Blob/BlobCoreSystem.cs
> -public sealed class BlobCoreSystem : SharedBlobCoreSystem
Потому что Shared пустой, соответственно и клиент
Я точно не шарю как делать предсказания на клиенте чтобы плавно все работало, но если будет подсказка то мог бы попытаться сделать

2024-09-18 17:50 UTC, Roudenn commented on Content.Server/Backmen/GameTicking/Rules/Components/BlobRuleComponent.cs
> +    public Dictionary<EntityUid, HashSet<Entity<BlobCoreComponent>>> StationCores = [];
Это перенесено из кода геймрула, теперь по идее геймрул не должен каждый раз пытаться ядра добавить а будет оперировать с ядрами из своего компонента, в общем удобно

2024-09-24 18:25 UTC, merged