Перевод вооружение, кары, типс и культа ядро.
Rxup/space-station-14 pull request #708
Opened 2024-07-26 17:34 UTC by CrimeMoot

## Описание PR
1. Перевод описание оружие, до которых дотянулись руки.
2. Исправление ftl перевод оружие в двух руках.
3. Перевод всех tips

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.

:cl:
- tweak: Локализация описаний оружие.
- tweak: Добавлена локализации Сердце из плоти и крови, и его анонсирование от ЦК.
- tweak: Перевод всех tips советов на русский. 
- tweak: Перевод кары.
- fix: Исправление неправильного отображение **gunrequireswield-component-examine**, не было написано на русском.

2024-07-26 18:02 UTC, nomad0260 commented
а зачем сами ямлки переводить?

2024-07-26 18:04 UTC, CrimeMoot commented
Перевод что к стулу не прикручено. Ну вот такое желание у меня почему-то.

2024-07-26 18:05 UTC, CrimeMoot commented
Вообще изначально я бельё новое переводил. Но устал

2024-07-26 18:07 UTC, nomad0260 commented
лучше найти косяки в нынешнем переводе или  то, что не переведено, а таких моментов довольно много

2024-07-26 18:13 UTC, CrimeMoot commented
Я нашёл только с держанием оружие в две руки.

2024-07-27 04:16 UTC, Rxup requested changes
Для начала посмотри что твой пр меняет.

2024-07-27 06:05 UTC, Roudenn commented
Перевод подсказок лучше на корвакс закинуть чтобы не было конфликтов если что

2024-07-27 09:48 UTC, CrimeMoot commented
А о как, окей. Корвакс так корвакс. А вообще странно - они вроде как были переведены. Но тут уже нет.

2024-07-27 09:48 UTC, closed without merging

2024-07-27 09:49 UTC, CrimeMoot commented
И да я вижу что он не то меняет. Т.к я перепутал.