Shotguns!
Rxup/space-station-14 pull request #721
Opened 2024-08-15 18:08 UTC by nomad0260

## Описание PR

Добавляет систему помпового оружия (портировано с смов), а так же небольшой ребаланс вооружения
**Медиа**

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Добавлено веселье!

2024-08-16 16:33 UTC, CrimeMoot commented
Честное слово - может не надо? Боже упаси.

2024-08-20 14:53 UTC, Rxup requested changes

2024-08-20 14:53 UTC, Rxup commented on Content.Client/Backmen/Weapons/PumpActionSystem.cs
> +        args.PushMarkup($"[bold]Press your [color=cyan]unique action[/color] keybind (Spacebar by default) to pump before shooting.[/bold]", 1);
можно перевести? :)

2024-08-20 14:53 UTC, Rxup commented on Content.Client/Backmen/Weapons/PumpActionSystem.cs
> +                : "You need to pump the gun first!";
перевод

2024-08-20 14:53 UTC, Rxup commented on Content.Shared/Backmen/Weapons/Common/UniqueActionSystem.cs
> +            Text = "Unique action",
перевод

2024-08-20 15:01 UTC, merged