Back To Lobby
Rxup/space-station-14 pull request #743
Opened 2024-09-14 10:25 UTC by trest100

## Описание PR
Добавлена кнопка возвращения в раунд

## Почему / Баланс
возможность игрокам возвращаться в раунд
## Технические детали

## Медиа

## Требования

- [ ] Я прочитал(а) и следую [Рекомендациям по оформлению Pull Request и Changelog](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ ] Я добавил(а) медиафайлы к этому PR или он не требует демонстрации в игре.

## Критические изменения

**Список изменений**

:cl: trest100
- add: кнопка возврата в лобби

2024-09-14 10:42 UTC, PuroSlavKing requested changes

2024-09-14 10:42 UTC, PuroSlavKing commented on Content.Shared/CCVar/CCVars.cs
> +         * Ghost Respawn
Почему в CCVar оффов? Говно переделывай.

2024-09-14 10:42 UTC, PuroSlavKing commented on Resources/Locale/ru-RU/ghost/ghost-gui.ftl
> +ghost-gui-return-to-round-button = Вернуться в раунд
Почему в папку общей локализации? Говно переделывай.

2024-09-14 10:44 UTC, trest100 commented on Content.Shared/CCVar/CCVars.cs
> +         * Ghost Respawn
> Почему в CCVar оффов? Говно переделывай.

потому что там уже юзаются сивары оффов, как юзать при этом сивары бэкмена, при условии - что у них одинаковые названия параметров - в душе не ебу

2024-09-14 10:52 UTC, PuroSlavKing commented on Content.Shared/CCVar/CCVars.cs
> +         * Ghost Respawn
пиздец

2024-09-15 11:12 UTC, KayzelW approved these changes

2024-09-15 11:15 UTC, merged