[Port] Combat Mode Indicator
Rxup/space-station-14 pull request #758
Opened 2024-09-18 18:21 UTC by PuroSlavKing

# Описание PR

Ахуенный, современный, комбат индикатор для однокнопочной боёвки.

## Медиа

https://github.com/user-attachments/assets/25891ad5-ebc5-4f66-85d2-5974dc00e3d4

## Тип PR

- [x] Feature
- [ ] Fix
- [ ] Tweak
- [ ] Balance
- [ ] Refactor
- [x] Port
- [ ] Translate
- [ ] Resprite

**Изменения**

:cl: PuroSlavKing
- add: Добавлен индикатор боевого режима.
- add: Добавлены звуки перехода в боевой режим.

2024-09-18 19:40 UTC, Rxup requested changes

2024-09-18 19:40 UTC, Rxup commented on Content.Client/CombatMode/CombatModeSystem.cs
> +        if (!TryComp<SpriteComponent>(uid, out var sprite))
Это функция вызывается очень часто, сделай плз через GetEntityQuery

2024-09-18 20:29 UTC, PuroSlavKing commented on Content.Client/CombatMode/CombatModeSystem.cs
> +        if (!TryComp<SpriteComponent>(uid, out var sprite))
> Это функция вызывается очень часто, сделай плз через GetEntityQuery

Сложно 😭

2024-09-19 02:06 UTC, CrimeMoot commented
Так смысле. Иконки должностей же у нас слева. 
Разве не лучше индикатор на право перенести? А не под бабл речи.

2024-09-19 04:24 UTC, PuroSlavKing commented
> Так смысле. Иконки должностей же у нас слева. 
> Разве не лучше индикатор на право перенести? А не под бабл речи.

Чем лучше видно - тем лучше

2024-09-20 07:13 UTC, trest100 reviewed
Ну норм , ч сказать замена попапа на спрайт с вызовом звука

2024-09-20 07:22 UTC, PuroSlavKing commented
> Ну норм , ч сказать замена попапа на спрайт с вызовом звука

лучше переведи его на GetEntityQuery

2024-09-20 09:19 UTC, CrimeMoot commented
Ну убери ты его направо под иконку должности...

2024-09-20 09:21 UTC, trest100 commented
> Ну убери ты его налево под иконку должности...

Ты ролик хоть посмотри где он отображается

2024-09-20 09:45 UTC, CrimeMoot commented
> Ты ролик хоть посмотри где он отображается 

Ну, справа. Так иконки то должностей у нас не справа - а слева. Справа у нас спич баблы.

2024-09-20 11:11 UTC, KayzelW approved these changes

2024-09-20 11:13 UTC, PuroSlavKing commented
@KayzelW сигма, но такие добавления нужно помечать

2024-09-20 11:53 UTC, Rxup approved these changes

2024-09-20 12:04 UTC, merged