[Tweak] Config Edit
Rxup/space-station-14 pull request #770
Opened 2024-09-20 14:02 UTC by PuroSlavKing

# Описание PR

## Медиа

## Тип PR

- [ ] Feature
- [ ] Fix
- [x] Tweak
- [ ] Balance
- [ ] Refactor
- [ ] Port
- [ ] Translate
- [ ] Resprite

**Изменения**

2024-09-20 15:49 UTC, Rxup requested changes
[ERRO] cfg: Trying to set unregistered variable 'emergency.emergency_early_launch_allowed'

2024-09-21 12:24 UTC, Rxup requested changes
уже обсуждали OOC во время раунда не будет

```
[ooc]
enable_during_round = true
```

2024-09-21 12:26 UTC, Rxup commented
также не понятна причина
```
[chat]
max_message_length = 5000
max_announcement_length = 1200
```
ттс это озвучивать не будет. Если делать меньше имеет смысл.

2024-09-21 12:35 UTC, PuroSlavKing commented
> также не понятна причина
> ```
> [chat]
> max_message_length = 5000
> max_announcement_length = 1200
> ```
> ттс это озвучивать не будет. Если делать меньше имеет смысл.

Вопрос не в том что ТТС, а в том, что чат действий и разговора объединён в один, из-за чего эмоут осмысленный лучше чем "перданул с подливой", просто невозможно написать, потому-что количество символов тупо не рассчитано на РП, из-за чего и случается ситуация, когда сидишь, пишешь, пишешь, стараешься, а сообщение исчезает, просто потому-что больше двух предложений написано и какое спрашивается РП в таком куполе может быть?

2024-09-21 12:49 UTC, PuroSlavKing commented
> > Вопрос не в том что ТТС (Оповещения может окей), а в том, что чат действий и разговора объединён в один, из-за чего эмоут осмысленный лучше чем "перданул с подливой", просто невозможно написать, потому-что количество символов тупо не рассчитано на РП, из-за чего и случается ситуация, когда сидишь, пишешь, пишешь, стараешься, а сообщение исчезает, просто потому-что больше двух предложений написано и какое спрашивается РП в таком куполе может быть?
> 
> учится писать так чтобы не ломать ттс.

А потом плачут, почему ЛРП, где отыгрыш, гиб, прыжок, победка

2024-09-21 12:50 UTC, nomad0260 commented
ты хочешь в игру добавить те самые ерп стены текста?

2024-09-21 12:52 UTC, PuroSlavKing commented
> ты хочешь в игру добавить те самые ерп стены текста?

даже в одной стене ЕРП, больше РП, чем на бекмене :trollface:

2024-09-21 13:09 UTC, PuroSlavKing commented
> уже обсуждали! OOC во время раунда не будет
> 
> ```
> [ooc]
> enable_during_round = true
> ```

Я называю это оттягивание неизбежного.

2024-09-21 13:33 UTC, merged