[Repsrite & Feature][Draft] Thruster
Rxup/space-station-14 pull request #774
Opened 2024-09-21 12:38 UTC by CrimeMoot

# Описание PR
Добавление в игру больше вариативности двигателей: Средний двигатель, Большой двигатель. Так же разновидность их окрашивание, в зависимости от того - куда хотите поставить.

## Тип PR
- [x] Feature
- [x] Resprite

:cl: CrimeMoot, TheGypsyBaron
- add: Добавлено веселье.

2024-09-21 12:41 UTC, CrimeMoot commented
Тут потом будет мне в магазин.

2024-09-21 13:34 UTC, CrimeMoot commented
А где блять.

2024-09-21 13:41 UTC, CrimeMoot commented
Короче картинки не будет мне лень заходить.

2024-09-21 13:43 UTC, PuroSlavKing requested changes

2024-09-21 13:43 UTC, PuroSlavKing commented on Resources/Locale/ru-RU/_backmen/entities/structures/shuttles/thrusters.ftl
> +    .desc = { ent-Thruster.desc }
не нужно по 50 раз повторять одно и тоже название, используй ту же логику, что и "{ ent-Thruster.desc }".

2024-09-21 13:43 UTC, PuroSlavKing commented on Resources/Textures/Backmen/Entities/Structures/Shuttles/thrusters.yml
> +        offset: 0, 2
у него прочность как у маленького, так не должно быть, чем больше - тем прочнее.

2024-09-21 13:43 UTC, PuroSlavKing commented on Resources/Textures/Backmen/Entities/Structures/Shuttles/thrusters.yml
> +        offset: 0, 3
у него прочность как у маленького, так не должно быть, чем больше - тем прочнее.

2024-09-21 13:43 UTC, PuroSlavKing commented on Resources/Textures/Backmen/Structures/Shuttles/thruster.rsi/meta.json
> +  "license": "CLA-BY-SA-3.0",
"CLA-BY-SA-3.0"? Такой лицензии не существует, используй "CC BY-NC-SA 3.0", а ещё лучше "CC BY-NC-SA 4.0"

2024-09-21 13:43 UTC, PuroSlavKing commented on Resources/Textures/Backmen/Structures/Shuttles/thruster_big.rsi/meta.json
> +  "license": "CLA-BY-SA-3.0",
"CLA-BY-SA-3.0"? Такой лицензии не существует, используй "CC BY-NC-SA 3.0", а ещё лучше "CC BY-NC-SA 4.0"

2024-09-21 13:43 UTC, PuroSlavKing commented on Resources/Textures/Backmen/Structures/Shuttles/thruster_large.rsi/meta.json
> +  "license": "CLA-BY-SA-3.0",
"CLA-BY-SA-3.0"? Такой лицензии не существует, используй "CC BY-NC-SA 3.0", а ещё лучше "CC BY-NC-SA 4.0"

2024-09-21 13:46 UTC, CrimeMoot commented on Resources/Textures/Backmen/Structures/Shuttles/thruster_large.rsi/meta.json
> +  "license": "CLA-BY-SA-3.0",
Не я делал. Уберу

2024-09-21 16:07 UTC, PuroSlavKing requested changes
Невозможно заспавнить двигатели, кроме маленького.
Так же нужны упаковки, чтоб был хоть какой-то вариант постройки в IC.

2024-09-22 04:24 UTC, CrimeMoot commented
С уходом @PuroSlavKing я отменяю данный PR и дальнейшие идеи. Т.к по больше части я хотел поддержать не сервер, а человека. Буду делать только для себя.

2024-09-22 04:24 UTC, closed without merging

2024-09-22 05:08 UTC, Rxup commented
> С уходом @PuroSlavKing я отменяю данный PR и дальнейшие идеи. Т.к по больше части я хотел поддержать не сервер, а человека. Буду делать только для себя.

я теперь буду тоже включать эмо режим, задолбали.