[Fix] Blob preset fix
Rxup/space-station-14 pull request #806
Opened 2024-10-01 13:31 UTC by Roudenn

# Описание PR
(Наверное) Исправляет ошибку с геймрулом блоба, когда после его убийства тут же вновь ставился код сигма и запускалась стадия начала.
Также теперь все тайлы блоба на одной станции снова учитываются (был баг который это сломал)
Тайлы ставятся с прежней скоростью, 3 в секунду

## Тип PR

- [ ] Feature
- [X] Fix
- [ ] Tweak
- [ ] Balance
- [ ] Refactor
- [ ] Port
- [ ] Translate
- [ ] Resprite

**Изменения**

2024-10-01 18:52 UTC, KayzelW requested changes

2024-10-01 18:52 UTC, KayzelW commented on Content.Server/Backmen/GameTicking/Rules/BlobRuleSystem.cs
> +        var blobCores = new Dictionary<EntityUid, HashSet<Entity<BlobCoreComponent>>>();
Зачем создавать структуру, типа её заполнять, а потом снова по ней итерироваться? Звучит как двойная работа * сёр в память...

2024-10-02 09:27 UTC, Roudenn commented on Content.Server/Backmen/GameTicking/Rules/BlobRuleSystem.cs
> +        var blobCores = new Dictionary<EntityUid, HashSet<Entity<BlobCoreComponent>>>();
Потому что перенося это в компонент оно ломается... Я просто откатил на время чтобы пофиксить режим

2024-10-02 09:27 UTC, Roudenn commented on Content.Server/Backmen/GameTicking/Rules/BlobRuleSystem.cs
> +        var blobCores = new Dictionary<EntityUid, HashSet<Entity<BlobCoreComponent>>>();
Позже надо вообще полностью переделать то как геймрул работает, потому что сейчас тяжело

2024-10-02 16:30 UTC, Roudenn commented
либо мёрджить сейчас либо блоб остаётся сломанным на долгое время

2024-10-02 16:48 UTC, merged