[Feature] Черта монолингва
Rxup/space-station-14 pull request #855
Opened 2024-10-20 18:11 UTC by korguzenok

# Описание PR

Добавляет в игру трейт [монолингива](https://ru.wikipedia.org/wiki/%D0%9C%D0%BE%D0%BD%D0%BE%D0%BB%D0%B8%D0%BD%D0%B3%D0%B2%D0%B8%D0%B7%D0%BC). 

Если что, исправляйте, я обязан был где-то наговнокодить.

## Тип PR

- [X] Feature
- [ ] Fix
- [ ] Tweak
- [ ] Balance
- [ ] Refactor
- [ ] Port
- [ ] Translate
- [ ] Resprite

**Изменения**

:cl: Sodka
- add: добавлена черта "Монолингв" которая убирает у вас возможность говорить и понимать Тау Кита (общий язык для всего экипажа станции)

2024-10-20 21:20 UTC, Rxup requested changes
ревью отписал в дс в личку

2024-10-20 23:49 UTC, korguzenok commented
Всё что надо изменил, работает и в обратку при удалении! Ненавижу гитхаб.

2024-10-21 07:05 UTC, Roudenn commented
Почему у тебя коммит с обновлением суб модуля? Его нельзя коммитить, его нужно только откатывать

2024-10-21 08:52 UTC, korguzenok commented
> Почему у тебя коммит с обновлением суб модуля? Его нельзя коммитить, его нужно только откатывать

Cмешной билд решил мне сабмодуль обновить. За подсказку спасибо, откатил.

2024-10-22 20:28 UTC, merged