[Tweak] New Tips
Rxup/space-station-14 pull request #856
Opened 2024-10-21 07:02 UTC by Roudenn

Добавлены новые подсказки! Вот и всё...

2024-10-21 08:32 UTC, idoffront commented
наоброт

2024-10-21 08:32 UTC, idoffront commented
пофикси там ошибочку

2024-10-21 08:41 UTC, Roudenn commented
> пофикси там ошибочку

Покажи сначала где, желательно через ревью

2024-10-22 00:56 UTC, nomad0260 requested changes

2024-10-22 00:56 UTC, nomad0260 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-37 = Вы можете нажать Пробел по умолчанию чтобы видеть немного дальше, либо же прицеливаться если вы держите оружие с прицелом!
Добавь что на пробел так же нужен для зарядки помпы

2024-10-22 01:43 UTC, nomad0260 commented
Это такой конец

2024-10-22 05:52 UTC, Roudenn commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-37 = Вы можете нажать Пробел по умолчанию чтобы видеть немного дальше, либо же прицеливаться если вы держите оружие с прицелом!
Не нормально что 2 действия противоречащих друг другу уделена одна кнопка, лучше поменяй с проблема на что-то другое, либо прицел по дефолту перенеси чтоб удобно было

2024-10-22 15:51 UTC, nomad0260 approved these changes

2024-10-22 15:51 UTC, merged