WonderDelta: Requem
Rxup/space-station-14 pull request #860
Opened 2024-10-22 20:31 UTC by trest100

# Описание PR
ГООООООООООООООООООООООООООООООООООООООЛ

## Медиа

## Тип PR

- [ ] Feature
- [ ] Fix
- [ ] Tweak
- [ ] Balance
- [ ] Refactor
- [ ] Port
- [ ] Translate
- [ ] Resprite

**Изменения**

2024-10-23 10:54 UTC, nomad0260 commented
Не делай его в драфт, пусть тесты проводятся

2024-10-23 12:06 UTC, nomad0260 requested changes

2024-10-23 12:06 UTC, nomad0260 commented on Resources/Prototypes/Tiles/floors.yml
> +  heatCapacity: 1000
в папку backmen перемести

2024-10-23 12:21 UTC, Rxup commented
@nomad0260 без мап рендера не принимай

2024-10-24 00:29 UTC, trest100 commented on Resources/Prototypes/Tiles/floors.yml
> +  heatCapacity: 1000
Это временные тайлы, которые просто копируют ID, они будут реворкнуты

2024-12-30 21:54 UTC, closed without merging