FOOTSTEPS [working now] + small renames (WD --> BACKMEN)
Rxup/space-station-14 pull request #861
Opened 2024-10-23 10:01 UTC by Woolfie-STR

Ну следы, ну работают теперь, да.
![image](https://github.com/user-attachments/assets/12612cad-1145-4432-8f49-1ecc00b52a84)

Ну и немного ренейма в комментариях :jokerge:

## Тип PR
- [x] Feature
- [ ] Fix
- [ ] Tweak
- [ ] Balance
- [ ] Refactor
- [x] Port
- [ ] Translate
- [ ] Resprite

**Изменения**
:cl: 
- add: Добавлены следы, которые появляются после ходьбы / перетягивания по жидкости (puddle)

2024-10-23 11:56 UTC, Rxup requested changes
нужно не много оптимизации

2024-10-23 11:56 UTC, Rxup commented on Content.Server/Fluids/EntitySystems/AbsorbentSystem.cs
> +        if (!TryComp<FootPrintComponent>(target, out _)) // Perform a check if it was a footprint that was clicked on
HasComp

2024-10-23 11:56 UTC, Rxup commented on Content.Shared/Backmen/FootPrint/FootPrintsComponent.cs
> +    public string[] DraggingPrint =
Желательно подписать что это layer, и саму RSI сюда добавить

2024-10-23 11:56 UTC, Rxup commented on Content.Server/Backmen/FootPrint/FootPrintsSystem.cs
> +        var entity = EntityManager.SpawnEntity(
Spawn(

2024-10-23 11:56 UTC, Rxup commented on Content.Server/Fluids/EntitySystems/AbsorbentSystem.cs
> +        var query = EntityQueryEnumerator<FootPrintComponent>();
Добавить
```     [Dependency] private readonly EntityLookupSystem _lookup = default!; ```
и тут использовать
``` _lookup.GetEntitiesInRange<FootPrintComponent>(Transform(target).Coordinates, 0.25f, LookupFlags.Dynamic | LookupFlags.Uncontained) ```

желательно HashSet сделать в виде привата в функции чтобы избежать allocate (в функции есть ext в аргументом, оффы рекомендуют избегать allocate для таких функций)

п.с. возможно флаги луткапа не правильные

2024-10-23 11:56 UTC, Rxup commented on Content.Server/Backmen/FootPrint/FootPrintsSystem.cs
> +        if (!TryComp<MobThresholdsComponent>(uid, out var mobThreshHolds) ||
в методах которые часто используются такие как OnMove и физика, лучше делать через Get
например
в классе ``` private EntityQuery<MapGridComponent> _gridQuery;```
в ``` public override void Initialize() ```
``` _gridQuery = GetEntityQuery<MapGridComponent>(); ```

и далее можно использовать _gridQuery.TryComp

2024-10-24 00:35 UTC, trest100 reviewed
Отправляем на тестовый сервер завтра вечером

2024-10-24 11:11 UTC, Rxup approved these changes

2024-10-24 20:12 UTC, merged